### PR TITLE
feat: services section

### PR DESCRIPTION
**Pull request by geethakash**
# Feature Services section ✨ 

Jira issue: [B20-2](https://bitzquad-com.atlassian.net/browse/B20-2)

 - responsive - sm md lg <

## Checklist

-   [x] Meets the acceptance criteria
-   [x] Tested all changes
-   [x] Project builds with `npm run static`
-   [x] No error nor warning in the console

-   [x] Does **not** break documented API behavior / changes are documented
-   [x] I updated the documentation to reflect the changes
-   [x] I fixed|updated|added unit tests and integration tests for each feature

-   [x] Stakeholder Approval

### lg 
localhost_3000_squad_2(1080p Desktop)

#### Test Environments

 Windows 11 

Visual Studio Code

#### References

-   [framer-motion](https://www.framer.com/motion/)
-   [Tailwind-CSS](https://tailwindcss.com/)

### CODE REVIEW

**Review by hariwij — CHANGES_REQUESTED** [review]
image
 image is not centered. check the img file.

**Review by hariwij — COMMENTED** [review]
image
i think it is better if remove 'view services' buttom form mobile view.

**Review by kesaralive — APPROVED** [review]
Approved ✅

**Review by HarshaAbeyvickrama — APPROVED** [review]
Good to merge

**Pull request merged**
