### PR TITLE
fix: squad page alignments 🐛

### PR DESCRIPTION
**Pull request by geethakash**
# FIX: Squad page alignments 🐛

Jira issue: [B20-33](https://bitzquad-com.atlassian.net/browse/B20-33)

 - add bz-container to squad page

## Checklist

-   [x] Meets the acceptance criteria
-   [x] Tested all changes
-   [x] Project builds with `npm run static`
-   [x] No error nor warning in the console

-   [x] Does **not** break documented API behavior / changes are documented
-   [x] I updated the documentation to reflect the changes
-   [x] I fixed|updated|added unit tests and integration tests for each feature

-   [x] Stakeholder Approval

### xl
localhost_3000_squad(768p Desktop) (1)

### 2xl
localhost_3000_squad(1080p Desktop) (2)

#### Test Environments

 Windows 11 

Visual Studio Code

#### References

-   [framer-motion](https://www.framer.com/motion/)
-   [Tailwind-CSS](https://tailwindcss.com/)

### CODE REVIEW

**Review by hariwij — APPROVED** [review]
Seems OK ✅

**Review by HarshaAbeyvickrama — CHANGES_REQUESTED** [review]
Better to Align the content to

- Left side - Bitzquad logo level
- Right side - Menu link level

This is the view I have
image

**Comment by geethakash** [comment]
> Better to Align the content to
> 
> * Left side - Bitzquad logo level
> * Right side - Menu link level
>
 
### Fixed🚑
### [_PREVIEW LINK_](https://bitzquad-com-2-0-c5ho5zmak-geethakash.vercel.app/squad) 🚀

**Review by HarshaAbeyvickrama — APPROVED** [review]
Approved and ready to merge

**Pull request merged**
