### PR TITLE
feat: single member detail page ✨ 

### PR DESCRIPTION
**Pull request by geethakash**
# Feature single member detail page ✨ 

Jira issue: [B20-23](https://bitzquad-com.atlassian.net/browse/B20-23)

 - responsive - sm md lg <
 - add initial animations

## Checklist

-   [x] Meets the acceptance criteria
-   [x] Tested all changes
-   [x] Project builds with `npm run static`
-   [x] No error nor warning in the console

-   [x] Does **not** break documented API behavior / changes are documented
-   [x] I updated the documentation to reflect the changes
-   [x] I fixed|updated|added unit tests and integration tests for each feature

-   [x] Stakeholder Approval

### lg 
localhost_3000_squad_2(1080p Desktop)

#### Test Environments

 Windows 11 

Visual Studio Code

#### References

-   [framer-motion](https://www.framer.com/motion/)
-   [Tailwind-CSS](https://tailwindcss.com/)

### CODE REVIEW

**Comment by HasinduLanka** [comment]
I think LinkedIn is a single word 🤔

**Comment by geethakash** [comment]
> I think LinkedIn is a single word 🤔



It just an array. You can change it what you want to..😁

**Review by IsuruVihan — APPROVED** [review]
The "Linked In" link label should be changed to "LinkedIn" (single word) and approved to merge to production after correcting the typo issue.

**Comment by geethakash** [comment]
> The "Linked In" link label should be changed to "LinkedIn" (single word) and approved to merge to production after correcting the typo issue.

It's not a issue.. we can change it while adding our real members list..😊
Look at the picture I added in reply as hasindu's comment.

**Review by HarshaAbeyvickrama — APPROVED** [review]
Correct the typo in the word LinkedIn and merge to dev

**Pull request merged**
