### PR TITLE
about section

### PR DESCRIPTION
**Pull request by hariwij**
# Feature about us page development✨ 

Jira issue: [B20-19](https://bitzquad-com.atlassian.net/browse/B20-19)

## Checklist

-   [x] Meets the acceptance criteria
-   [x] Tested all changes
-   [x] Project builds with `npm run static`
-   [x] No error nor warning in the console

-   [x] Does **not** break documented API behavior / changes are documented
-   [x] I updated the documentation to reflect the changes
-   [x] I fixed|updated|added unit tests and integration tests for each feature

-   [x] Stakeholder Approval

### sm

image

### md
image

### lg 
image
image

#### Test Environments

 Windows 11 

Visual Studio Code

#### References

-   [framer-motion](https://www.framer.com/motion/)
-   [Tailwind-CSS](https://tailwindcss.com/)

### CODE REVIEW

**Review by geethakash — CHANGES_REQUESTED** [review]
Screenshot 2022-08-15 114306

there are crops in bg text.. other than that everything is fine.

**Comment by HarshaAbeyvickrama** [comment]
> Screenshot 2022-08-15 114306
> 
> there are crops in bg text.. other than that everything is fine.

There are no issues in my view

image
image

**Review by HarshaAbeyvickrama — APPROVED** [review]
Approved

**Review by IsuruVihan — CHANGES_REQUESTED** [review]
It's better if we can add these shading effects (in "sm") for both "lg", and "md" sizes as well.

**sm**


**lg & md**

**Review by geethakash — COMMENTED** [review]
Approved & ready to merge 🔀

**Review by geethakash — APPROVED** [review]
Approved & ready to merge 🔀

**Pull request merged**
