### PR TITLE
fix: sidemenu responsive and overlay 🐛

### PR DESCRIPTION
**Pull request by geethakash**
# FIX: Sidemenu responsive and overlay implementation 

Jira issue: 
[B20-26](https://bitzquad-com.atlassian.net/browse/B20-26)
[B20-20](https://bitzquad-com.atlassian.net/browse/B20-29)

 - add backdrop blur to sidemenu overlay 
 - change font size in sidemenu navigation links
 - fix responsive issue in desktop xl screens

## Checklist

-   [x] Meets the acceptance criteria
-   [x] Tested all changes
-   [x] Project builds with `npm run static`
-   [x] No error nor warning in the console

-   [x] Does **not** break documented API behavior / changes are documented
-   [x] I updated the documentation to reflect the changes
-   [x] I fixed|updated|added unit tests and integration tests for each feature

-   [x] Stakeholder Approval

#### Test Environments

 Windows 11 

Visual Studio Code

#### References

-   [framer-motion](https://www.framer.com/motion/)
-   [Tailwind-CSS](https://tailwindcss.com/)

### CODE REVIEW

**Review by hariwij — CHANGES_REQUESTED** [review]
image

Side menu has overflow and  its scrolling down.

image

Gap between social links need to fix.

**Comment by geethakash** [comment]
### fix: sidemenu overflow scrolling

### [PREVIEW URL](https://bitzquad-com-2-0-nrploxgjs-geethakash.vercel.app/)

**Review by HarshaAbeyvickrama — CHANGES_REQUESTED** [review]
- Overlay looks good and clean
- There is the vertical scroll in the sidemenu still.

**Review by IsuruVihan — CHANGES_REQUESTED** [review]
- It's better if we can align "YouTube", "Academy", "Twitter", and "Facebook" link labels in the same vertical column.

**Comment by geethakash** [comment]
### fix: sidemenu overflow scrolling

### [PREVIEW URL](https://bitzquad-com-2-0-fy82j7ha8-geethakash.vercel.app/)

@IsuruVihan  @HarshaAbeyvickrama

**Review by HarshaAbeyvickrama — APPROVED** [review]
Alignments are correct and vortical scroll has been removed.  Good to merge

**Review by kesaralive — APPROVED** [review]
✅ good to merge

**Pull request merged**
